name: docs
on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                  python-version: 3.9
            - name: Install GDAL
              run: |
                  python -m pip install --upgrade pip
                  pip install --find-links=https://girder.github.io/large_image_wheels --no-cache GDAL pyproj 
            - name: Test GDAL installation
              run: |
                  python -c "from osgeo import gdal"
                  gdalinfo --version
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install --no-cache-dir Cython
                  pip install -r requirements.txt
            - name: PKG-TEST
              run: |
                  python -m unittest discover tests/
            - run: python -m pip install --upgrade pip
            - run: pip install mkdocs-material mkdocstrings mkdocstrings-python-legacy mkdocs-git-revision-date-plugin mkdocs-jupyter ipykernel
            - run: mkdocs gh-deploy --force
