on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

name: Windows build
jobs:
    test-windows:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install miniconda
              uses: conda-incubator/setup-miniconda@v2
              with:
                  auto-activate-base: true
                  python-version: 3.9
            - name: Install GDAL
              run: conda install -c conda-forge gdal=3.5.0 --yes
            - name: Test GDAL installation
              run: |
                  python -c "from osgeo import gdal"
                  gdalinfo --version
            - name: Install rasterio
              run: conda install -c conda-forge rasterio --yes
            - name: Test rasterio installation
              run: |
                  python -c "import rasterio"
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install --no-cache-dir Cython
                  pip install -r requirements.txt
                  pip install .
            # - name: PKG-TEST
            #   run: |
            #       python -m unittest discover tests/